trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  displayName: 'Install Terraform'
  inputs:
    targetType: 'inline'
    script: |
      curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      sudo apt-get update && sudo apt-get install terraform -y
      terraform --version

- task: AzureCLI@2
  displayName: 'Terraform Init & Apply'
  inputs:
    azureSubscription: 'testing'   # Replace with your Service Connection name
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      cd terraform-project
      terraform init
      terraform plan -var-file=terraform.tfvars -out=tfplan
      terraform apply -auto-approve tfplan